# Generated by Django 4.1.1 on 2022-09-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_author_managers_remove_author_date_joined_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="rate",
            field=models.DecimalField(decimal_places=1, max_digits=2),
        )
    ]
