# Generated by Django 4.1.1 on 2022-09-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("catalog", "0005_alter_country_options")]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
