# Generated by Django 4.1.1 on 2022-09-23 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("catalog", "0006_alter_author_photo_alter_book_image")]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name_plural": "counrties"},
        )
    ]
