# Generated by Django 4.1.1 on 2022-09-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("catalog", "0007_alter_country_options")]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"ordering": ["name"], "verbose_name_plural": "countries"},
        )
    ]
