# Generated by Django 4.1.1 on 2022-09-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("catalog", "0008_alter_country_options")]

    operations = [
        migrations.AlterModelOptions(name="book", options={"ordering": ["rate"]})
    ]
